services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'rootPassword*01'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'database_name'
            MYSQL_USER: 'awesomeuser'
            MYSQL_PASSWORD: 'userpassword*01'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'msyqlv:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p rootPassword*01'
            retries: 3
            timeout: 5s
volumes:
    msyqlv:
        driver: local